/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ZSong' at '6/26/16 9:18 AM' with Gradle 2.11
 *
 * @author ZSong, @date 6/26/16 9:18 AM
 */
public class Library {
  public boolean someLibraryMethod() {
    return true;
  }

  public int addNumbers(int num1, int num2) {
    return num1 + num2;
  }
}
