import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import static org.testng.Assert.assertTrue;
import static org.testng.Assert.assertEquals;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library --with testng'
 * by 'ZSong' at '6/26/16 9:18 AM' with Gradle 2.11
 *
 * @author ZSong, @date 6/26/16 9:18 AM
 */
public class LibraryTest {

  Library _library;
  @BeforeTest
  public void setup() {
    _library = new Library();
  }

  @Test
  public void someLibraryMethodReturnsTrue() {
    assertTrue(_library.someLibraryMethod(), "someLibraryMethod should return 'true'");
  }

  @Test
  public void addNumberTest() {
    int num1 = 2;
    int num2 = 3;
    int res = _library.addNumbers(num1, num2);
    assertEquals(res, 5);
  }


}
